##backgrounds 
image bg pcbang = "bg/light_lancenter_720.jpg"
image bg streetday = "bg/street_day.jpg"
image bg apartmentday = "bg/apartment_day.jpg"
image bg apartmentnight = "bg/apartment_night.jpg"
image bg darkpcbang = "bg/dark_final.jpg"
image bg streetnight = "bg/street_night.jpg"
image bg streetside = "bg/streetside_morning.jpg"
image bg streetsidenight = "bg/streetside_night.jpg"
image bg streetside2 = "bg/streetside2_morning.jpg"
image bg streetside2night2 = "bg/streetside2_night.jpg"
image bg streetside2night = "bg/streetside2_night2.jpg"
image bg studio = "bg/studio.jpg"
image bg cafe = "bg/cafe_lounge.jpg"
image bg parkday = "bg/park_day.jpg"
image bg parknight = "bg/park_night.jpg"
image bg booth = "bg/studiobooth.jpg"
image bg house = "bg/team.jpg"
image bg store = "bg/store.jpg"
image storebig = "bg/storebig.jpg"
image bg boardroom = "bg/boardroom.jpg"
image bg city = "bg/skyline.jpg"
image bg citybig = "bg/skylinebig.jpg"
image bg trendy = "bg/bar.jpg"
image bg hallway = "bg/hallway.jpg"
image bg hallway2 = "bg/hallway2.jpg"
image bg stage = "bg/stage.jpg"
image bg backstage = "bg/backstage.jpg"
image bg rain = "bg/apartment_rain.jpg"

image blacksolid = "bg/black.jpg"
image swoosh1 = "bg/swoosh1.png"
image swoosh1 yellow= "bg/swoosh1_yellow.png"
image swoosh2 yellow= "bg/swoosh2_yellow.png"
image swoosh2 = "bg/swoosh2.png"

image sky1 = "bg/SKY1ED.png"
image sky2 = "bg/SKY2.png"
image sky3 = "bg/SKY3.png"
image sky4 = "bg/SKY4.png"
image sky5 = "bg/SKY5.png"
image sky6 = "bg/sky6.jpg"
#cg

image bg cg11 = "bg/CG11a.jpg"
image bg cg12 = "bg/CG12a.jpg"
image bg cg13 = "bg/CG13.jpg"
image bg cg21 = "bg/CG21a.jpg"
image bg cg22 = "bg/CG22a.jpg"
image bg cg3 = "bg/CG3a.jpg"
image bg cg4 = "bg/CG4a.jpg"
image bg cg5 = "bg/CG5a.jpg"

image jettbaneling = "ingame/jettbaneling.png"
image jettwalloff = "ingame/jettwalloff.png"
image jettwin = "ingame/jettwin.png"
image jettzerg = "ingame/jettzerg.png"
image rival2rax = "ingame/rival2rax.png"
image rivaldefends = "ingame/rivaldefends.png"
image rivalfrontfalls = "ingame/rivalfrontfalls.png"
image rivallose = "ingame/rivallose.png"
image rivalmedivac = "ingame/rivalmedivac.png"
image rivalopening = "ingame/rivalopening.png"
image rivalopeningchoice = "ingame/rivalopeningchoice.jpg"
image rivalopeningchoiceselected = "ingame/rivalopeningchoiceselected.jpg"
image rivalwarpprism = "ingame/rivalwarpprism.png"
image rivalzealot = "ingame/rivalzealot.png"
image thirdflying = "ingame/thirdflying.png"
image rivalmid = "ingame/rivalmid.jpg"
image rivaldropped = "ingame/rivaldropped.png"

#demo 1 battles
image apartmentgame1 = "ingame/apartmentgame1-scout.png"
image apartmentgame2 = "ingame/apartmentgame2-prism.png"
image apartmentgame3 = "ingame/apartmentgame3-gg.png"

image tourneyzerg1 = "ingame/tourneyzerg1.png"
image tourneyzerg2 = "ingame/tourneyzerg2.png"
image tourneyzerg3 = "ingame/tourneyzerg3.png"

image tvtaccel1 = "ingame/tvtaccel1.png"
image tvtaccel2 = "ingame/tvtaccel2.png"
image tvtaccel3 = "ingame/tvtaccel3.png"
image tvtaccel4 = "ingame/tvtaccel4.png"
image tvtaccel5 = "ingame/tvtaccel5.png"

#stunt demo

image bg stuntbattle1 = "ingamedemo/1stuntstartterran.png"
image bg stuntbattle2 = "ingamedemo/2stuntcannonterran.png"
image bg stuntbattle3 = "ingamedemo/3stuntscvdeathterran.png"
image bg stuntbattle4 = "ingamedemo/4stuntattackcannonterran.png"
image bg stuntbattle5 = "ingamedemo/5stuntattackcannonterran.png"
image bg stuntbattle6 = "ingamedemo/6stuntattackprobeterran.png"
image bg stuntbattle7 = "ingamedemo/7stuntattackpylongterran.png"
image bg stuntbattle8 = "ingamedemo/8stuntchoiceterran.png"
image bg stuntbattle9 = "ingamedemo/9stuntbunkerupterran.png"
image bg stuntbattle10 = "ingamedemo/10stuntzealotrampterran.png"
image bg stuntbattle11 = "ingamedemo/11stuntzealotdieterran.png"
image bg stuntbattle12 = "ingamedemo/12stuntmachwinterran.png"
image bg stuntbattle13 = "ingamedemo/13stuntmachwinterran.png"



